apiVersion: v1
kind: Config
current-context: admin@development
clusters:
  - name: development
    cluster:
      certificate-authority: ca.crt
      server: https://172.16.0.52:6443
contexts:
  - name: admin@development
    context:
      cluster: development
      user: admin
users:
  - name: admin
    user:
      client-certificate: admin.crt
      client-key: admin.key